stages:
  - build
  - deploy

variables:
  NAME: appointments-consumer

# build-dev:
#   stage: build
#   variables:
#     SERVICE_ACCOUNT: $DEV_GCP_DEPLOY_SERVICE_ACCOUNT
#     PROJECT_ID: soundheart-dev-94cc1
#     SERVICES_ENV: $SERVICES_DEV_ENV
#   before_script:
#     - echo $SERVICE_ACCOUNT | base64 --decode >> key.json
#     - gcloud auth activate-service-account --key-file key.json
#     - gcloud config set project $PROJECT_ID
#   script:
#     - gcloud builds submit --tag gcr.io/$PROJECT_ID/$NAME
#   only:
#     - main
#   tags:
#     - kubernetes

deploy-dev:
  stage: deploy
  variables:
    SERVICE_ACCOUNT: $DEV_GCP_DEPLOY_SERVICE_ACCOUNT
    PROJECT_ID: soundheart-dev-94cc1
    SERVICES_ENV: $SERVICES_DEV_ENV
    SECRET_YAML: $SECRET_DEV_YAML
  before_script:
    - export PROJECT_ID=soundheart-dev-94cc1
    - echo $SERVICE_ACCOUNT | base64 --decode >> key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project $PROJECT_ID
    - echo $SECRET_YAML | base64 --decode >> k8s/secret.yaml
    - gcloud container clusters get-credentials event-driven-cluster --zone us-central1-c --project $PROJECT_ID
  script:
    - kubectl apply -f k8s/secret.yaml
    - kubectl apply -f k8s/deployment.yaml
    - kubectl set image deployment/appointments-consumer-deployment appointments-consumer=gcr.io/$PROJECT_ID/$NAME:latest
    - kubectl describe deployment appointments-consumer-deployment
    - kubectl rollout restart deployment appointments-consumer-deployment
  # needs:
  #   - build-dev
  only:
    - main
  tags:
    - kubernetes
