stages:
  - build
  - deploy

variables:
  NAME: appointments-consumer

build-dev:
  stage: build
  variables:
    SERVICE_ACCOUNT: $DEV_GCP_DEPLOY_SERVICE_ACCOUNT
    PROJECT_ID: soundheart-dev-94cc1
    SERVICES_ENV: $SERVICES_DEV_ENV
  before_script:
    - echo $SERVICE_ACCOUNT | base64 --decode >> key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project $PROJECT_ID
  script:
    - gcloud builds submit --tag gcr.io/$PROJECT_ID/$NAME
  only:
    - main
  tags:
    - kubernetes

deploy-dev:
  stage: deploy
  variables:
    SERVICE_ACCOUNT: $DEV_GCP_DEPLOY_SERVICE_ACCOUNT
    PROJECT_ID: soundheart-dev-94cc1
    SERVICES_ENV: $SERVICES_DEV_ENV
  before_script:
    - echo $SERVICE_ACCOUNT | base64 --decode >> key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project $PROJECT_ID
  script:
    - kubectl apply -f k8s/secret.yaml
    - kubectl apply -f k8s/deployment.yaml
  needs:
    - build-dev
  only:
    - main
  tags:
    - kubernetes
